services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "8081:8080"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_CREDENTIALS_USR}
      POSTGRES_PASSWORD: ${DB_CREDENTIALS_PSW}
      POSTGRES_DB: employee_management_db
    ports:
      - "5433:5432" # Host port 5433, container port 5432
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/employee_management_db
      DB_CREDENTIALS_USR: ${DB_CREDENTIALS_USR}
      DB_CREDENTIALS_PSW: ${DB_CREDENTIALS_PSW}
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket for Jenkins access
      - ./app_logs:/app/logs # Add volume for app logs if required (optional)
    entrypoint: [ "sh", "-c", "sleep 10 && java -jar /app.jar" ]

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  postgres_data: {}
