FROM jenkins/jenkins:lts

USER root

# Install Docker CLI (docker.io) and Docker Compose
RUN apt-get update && apt-get install -y \
    docker.io \
    curl && \
    curl -L "https://github.com/docker/compose/releases/download/v2.32.1/docker-compose-darwin-aarch64" -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
