FROM jenkins/jenkins:lts

USER root

# Install Docker CLI and Docker Compose
RUN apt-get update && apt-get install -y docker.io curl
RUN curl -fsSL "https://github.com/docker/compose/releases/download/v2.32.1/docker-compose-linux-armv6" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose
RUN docker --version && /usr/local/bin/docker-compose --version
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Expose ports for Jenkins
EXPOSE 8080 50000
