services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root # Ensure Jenkins runs with sufficient privileges
    build:
      context: .
      dockerfile: Dockerfile.jenkins # Add Docker and Compose to Jenkins container
    volumes:
      - /var/jenkins_home:/var/jenkins_home # Persist Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock # Share Docker socket
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock # Point Jenkins to the host's Docker daemon
    ports:
      - "8081:8080" # Expose Jenkins on localhost:8081
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_CREDENTIALS_USR}
      POSTGRES_PASSWORD: ${DB_CREDENTIALS_PSW}
      POSTGRES_DB: employee_management_db
    ports:
      - "5433:5432" # Host port 5433, container port 5432
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile.app # Reference the Dockerfile.app for springboot-application
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/employee_management_db
      DB_CREDENTIALS_USR: ${DB_CREDENTIALS_USR}
      DB_CREDENTIALS_PSW: ${DB_CREDENTIALS_PSW}
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./app_logs:/app/logs # Persist application logs
    entrypoint: [ "sh", "-c", "sleep 10 && java -jar /app.jar" ]

networks:
  app-network:
    name: app-network
    driver: bridge
    external: true

volumes:
  postgres_data: {}
