services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    external: true
