services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root # Ensure Jenkins runs with sufficient privileges
    build:
      context: .
      dockerfile: Dockerfile.jenkins # Add Docker and Compose to Jenkins container
    volumes:
      - /var/jenkins_home:/var/jenkins_home # Persist Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock # Share Docker socket
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock # Point Jenkins to the host's Docker daemon
    ports:
      - "8081:8080" # Expose Jenkins on localhost:8081
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
    external: true
