services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      DB_URL: jdbc:postgresql://employee-management-db.clcqqu684nm0.us-east-1.rds.amazonaws.com:5432/ems_db
      DB_CREDENTIALS_USR: ${DB_CREDENTIALS_USR}
      DB_CREDENTIALS_PSW: ${DB_CREDENTIALS_PSW}
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    external: true
